version: "3.4"

services:
    mongo-db:
        container_name: mongo-db
        image: mongo:4.4
        restart: always
        volumes:
          - ./.docker/mongodb/dbdata:/data/db
          - ./.docker/mongodb/configdb:/data/configdb
        environment:
          MONGO_INITDB_ROOT_USERNAME: cod3r
          MONGO_INITDB_ROOT_PASSWORD: cod3r
          MONGO_INITDB_DATABASE: cod3r-knowledge
        networks:
          - knowledge
        ports:
          - 27017:27017
    
    mongo-express:
        container_name: mongo-express
        image: mongo-express:0.54.0
        restart: always
        ports:
          - 8083:8081
        depends_on:
          - mongo-db
        environment:
          ME_CONFIG_MONGODB_SERVER: mongo-db
          ME_CONFIG_MONGODB_AUTH_USERNAME: cod3r
          ME_CONFIG_MONGODB_AUTH_PASSWORD: cod3r
          ME_CONFIG_MONGODB_ADMINUSERNAME: cod3r
          ME_CONFIG_MONGODB_ADMINPASSWORD: cod3r
        networks:
          - knowledge
networks:
    knowledge:
        driver: bridge